import discord
from discord.ext import commands


class Info(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self._last_member = None

    @commands.command(name="help")
    async def help(self, ctx):
        # Note that commands made only for the owner of the bot are not listed here.
        embed = discord.Embed(
            title="Doctrine :: Help",
            description="Doctrine bot commands are:",
            color=discord.Colour.from_rgb(109, 255, 234)
        )
        embed.add_field(
            name="Random map",
            value=f"> Responds with a randomly selected map from the map pool \
                    > as generated by label constraints. _Negative labels_ note the absense of a feature.\n \
                    > ```{self.bot.command_prefix}randmap label -label``` \
                    Label can be: walled, open, land, hybrid, water, ponds, elevation, tc",
            inline=False
        )
        embed.add_field(
            name="Hello World",
            value=f"> Placeholder test command for devs.",
            inline=False
        )

        await ctx.send(embed=embed)



def setup(bot):
    bot.add_cog(Info(bot))
